###################################################################################################

docker_engine_word: docker

###################################################################################################

docker_engine_support:

  - linux-x86_64

###################################################################################################

docker_engine_platform    : '{{ facts_system }}'
docker_engine_architecture: '{{ facts_architecture }}'

###################################################################################################

docker_engine_major    : 1
docker_engine_minor    : 10
docker_engine_revision : 3
docker_engine_sha256sum: d0df512afa109006a450f41873634951e19ddabf8c7bd419caeb5a526032d86d

###################################################################################################

docker_engine_version: '{{ docker_engine_major }}.{{ docker_engine_minor }}.{{ docker_engine_revision }}'

###################################################################################################

docker_engine_filename: '{{ docker_engine_word }}-{{ docker_engine_version }}'

###################################################################################################

docker_engine_src_base: https://get.docker.com/builds
docker_engine_src_arch: '{{ docker_engine_platform | capitalize }}/{{ docker_engine_architecture }}'
docker_engine_src_url : '{{ docker_engine_src_base }}/{{ docker_engine_src_arch }}/{{ docker_engine_filename }}'

###################################################################################################

docker_engine_dest_base_path : /usr/local/bin
docker_engine_dest_base_mode : '0755'
docker_engine_dest_base_owner: root
docker_engine_dest_base_group: root

docker_engine_dest_path : '{{ docker_engine_dest_base_path }}/{{ docker_engine_filename }}'
docker_engine_dest_mode : '0755'
docker_engine_dest_owner: root
docker_engine_dest_group: root

###################################################################################################

docker_engine_link_base_path : /usr/bin
docker_engine_link_base_mode : '0755'
docker_engine_link_base_owner: root
docker_engine_link_base_group: root

docker_engine_link_name: '{{ docker_engine_word }}'
docker_engine_link_path: '{{ docker_engine_link_base_path }}/{{ docker_engine_link_name }}'

###################################################################################################

docker_engine_config_base_path : /etc/{{ docker_engine_word }}
docker_engine_config_base_mode : '0755'
docker_engine_config_base_owner: root
docker_engine_config_base_group: root

docker_engine_config_name: config.json
docker_engine_config_src : '{{ docker_engine_config_name }}.j2'
docker_engine_config_dest: '{{ docker_engine_config_base_path }}/{{ docker_engine_config_name }}'
docker_engine_config_mode: '0644'

###################################################################################################

docker_engine_process_control: systemd

###################################################################################################
