###################################################################################################

- name: systemd | import

  include_vars: systemd

###################################################################################################

- name: systemd | configure

  template: src={{ docker_engine_systemd_config_src  }}
           dest={{ docker_engine_systemd_config_dest }}
           mode={{ docker_engine_systemd_config_mode }}

  register: configure

###################################################################################################

- name: systemd | reload

  when: configure.changed

  command: systemctl daemon-reload

###################################################################################################

- name: systemd | enable

  command: systemctl enable {{ docker_engine_systemd_config_name }}

###################################################################################################

- name: systemd | start

  command: systemctl start {{ docker_engine_systemd_config_name }}

###################################################################################################
