###################################################################################################

- name: systemd | import

  include_vars: systemd

###################################################################################################

- name: systemd | socket | configure

  template: src={{ docker_engine_systemd_socket_config_src  }}
           dest={{ docker_engine_systemd_socket_config_dest }}
           mode={{ docker_engine_systemd_socket_config_mode }}

  register: systemd_socket

###################################################################################################

- name: systemd | service | configure

  template: src={{ docker_engine_systemd_service_config_src  }}
           dest={{ docker_engine_systemd_service_config_dest }}
           mode={{ docker_engine_systemd_service_config_mode }}

  register: systemd_service

###################################################################################################

- name: systemd | reload

  when: systemd_socket.changed
     or systemd_service.changed

  command: systemctl daemon-reload

###################################################################################################

- name: systemd | socket | enable

  service: name={{ docker_engine_systemd_socket_name }} enabled=true

###################################################################################################

- name: systemd | socket | restart

  when: configuration.changed
     or systemd_socket.changed

  service: name={{ docker_engine_systemd_socket_name }} state=restarted

###################################################################################################

- name: systemd | socket | start

  service: name={{ docker_engine_systemd_socket_name }} state=started

###################################################################################################

- name: systemd | service | enable

  service: name={{ docker_engine_systemd_service_name }} enabled=true

###################################################################################################

- name: systemd | service | restart

  when: configuration.changed
     or systemd_service.changed

  service: name={{ docker_engine_systemd_service_name }} state=restarted

###################################################################################################

- name: systemd | service | start

  service: name={{ docker_engine_systemd_service_name }} state=started

###################################################################################################
