###################################################################################################

- name: systemd | import

  include_vars: systemd

###################################################################################################

- name: systemd | unit

  template: src={{ docker_engine_systemd_config_src  }}
           dest={{ docker_engine_systemd_config_dest }}
           mode={{ docker_engine_systemd_config_mode }}

  register: systemd

###################################################################################################

- name: systemd | reload

  when: systemd.changed

  command: systemctl daemon-reload

###################################################################################################

- name: systemd | enable

  service: name={{ docker_engine_systemd_config_name }} enabled=true

###################################################################################################

- name: systemd | restart

  when: systemd.changed

  service: name={{ docker_engine_systemd_config_name }} state=restarted

###################################################################################################

- name: systemd | start

  service: name={{ docker_engine_systemd_config_name }} state=started

###################################################################################################
