###################################################################################################

- name: systemd | import

  include_vars: systemd

###################################################################################################

- name: systemd | service | configure

  template: src={{ docker_engine_systemd_service_config_src  }}
           dest={{ docker_engine_systemd_service_config_dest }}
           mode={{ docker_engine_systemd_service_config_mode }}

  register: systemd_service

###################################################################################################

- name: systemd | reload

  when: systemd_service.changed

  command: systemctl daemon-reload

###################################################################################################

- name: systemd | service | enable

  service: name={{ docker_engine_systemd_service_name }} enabled=true

###################################################################################################

- name: systemd | restart

  when: configuration.changed
     or systemd_service.changed

  service: name={{ docker_engine_systemd_service_name }} state=restarted

###################################################################################################

- name: systemd | start

  service: name={{ docker_engine_systemd_service_name }} state=started

###################################################################################################
