###################################################################################################

- name: verify | support

  assert:
    that:

      - '"{{ docker_engine_platform }}-{{ docker_engine_architecture }}" in docker_engine_support'

###################################################################################################
