###################################################################################################

- name: verify

  assert:
    that:

      - user_name is defined
      - user_name is not none
      - user_name | length > 0

      - user_home is defined
      - user_home is not none
      - user_home | length > 0

  tags:
    - asteria
    - user

###################################################################################################

- name: base | discover

  shell: dirname {{ user_home }}

  changed_when: false

  register: base

  tags:
    - asteria
    - user

###################################################################################################

- name: base | touch

  file: dest={{ base.stdout }} state=directory

  tags:
    - asteria
    - user

###################################################################################################

- name: group

  group: name={{ user_group }}

  tags:
    - asteria
    - user

###################################################################################################

- name: user

  user:  name={{ user_name  }}
        group={{ user_group }}
        shell={{ user_shell }}
   createhome=no

  tags:
    - asteria
    - user

###################################################################################################

- name: home

  file: dest={{ user_home  }}
       owner={{ user_name  }}
       group={{ user_group }}
        mode={{ user_mode  }}
       state=directory

  tags:
    - asteria
    - user

###################################################################################################
