###################################################################################################

- include: verify.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - verify

###################################################################################################

- include: dependencies.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - dependencies

###################################################################################################

- include: download.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - download

###################################################################################################

- include: install.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - install

###################################################################################################

- name: data | touch

  sudo_user: '{{ consul_server_user }}'

  file: dest={{ consul_server_data_base }} state=directory

  tags:
    - asteria
    - hashicorp
    - consul
    - server

###################################################################################################

- name: config | touch

  sudo_user: '{{ consul_server_user }}'

  file: dest={{ consul_server_config_base }} state=directory

  tags:
    - asteria
    - hashicorp
    - consul
    - server

###################################################################################################

- name: config | configure

  sudo_user: '{{ consul_server_user }}'

  template: src={{ consul_server_config_src  }}
           dest={{ consul_server_config_dest }}

  register: config

  tags:
    - asteria
    - hashicorp
    - consul
    - server

###################################################################################################

- include: systemd.yml

  when: consul_server_process_control == 'systemd'

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - systemd

###################################################################################################
