###################################################################################################

- name: verify | inventory

  assert:
    that:

      - groups[consul_server_inventory_group] | count > 0

###################################################################################################

- name: verify | support

  assert:
    that:

      - '"{{ consul_server_platform }}-{{ consul_server_architecture }}" in consul_server_support'

###################################################################################################
