###################################################################################################

- include: verify.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server

###################################################################################################

- name: debian | dependencies

  when: shared_os_family == 'debian'

  with_items: consul_server_dependencies

  apt : name={{ item }} state=present install_recommends=false

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - debian

###################################################################################################

- name: redhat | dependencies

  when: shared_os_family == 'redhat'

  with_items: consul_server_dependencies

  yum : name={{ item }} state=present

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - redhat

###################################################################################################

- name: zip | base

  file: dest={{ consul_server_zip_dest_base }} state=directory

  tags:
    - asteria
    - hashicorp
    - consul
    - server

###################################################################################################

- name: zip | download

  get_url: url={{ consul_server_zip_src_url   }}
     sha256sum={{ consul_server_zip_sha256sum }}
          dest={{ consul_server_zip_dest_path }}

  tags:
    - asteria
    - hashicorp
    - consul
    - server

###################################################################################################
