###################################################################################################

- name: ping

  ping:

  tags:
    - asteria
    - hashicorp
    - consul
    - server

###################################################################################################
