###################################################################################################

- include: verify.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - verify

###################################################################################################

- include: dependencies.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - dependencies

###################################################################################################

- include: download.yml

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - download

###################################################################################################
