###################################################################################################

- name: systemd | import

  include_vars: systemd

###################################################################################################

- name: systemd | systemd

  template: src={{ consul_server_systemd_config_src  }}
           dest={{ consul_server_systemd_config_dest }}
           mode={{ consul_server_systemd_config_mode }}

  register: systemd

###################################################################################################

- name: systemd | reload

  when: systemd.changed

  command: systemctl daemon-reload

###################################################################################################

- name: systemd | enable

  service: name={{ consul_server_systemd_config_name }} enabled=true

###################################################################################################

- name: systemd | restart

  when: install.changed
     or config.changed
     or systemd.changed

  service: name={{ consul_server_systemd_config_name }} state=restarted

###################################################################################################

- name: systemd | start

  service: name={{ consul_server_systemd_config_name }} state=started

###################################################################################################
