###################################################################################################

- name: verify

  assert:
    that:

      - '"{{ consul_server_platform }}-{{ consul_server_architecture }}" in consul_server_support'

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - verify

###################################################################################################
