###################################################################################################

- name: verify | setup

  assert:
    that:

      - module_setup is defined
      - module_setup is not none
      - module_setup

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - verify

###################################################################################################

- name: verify | support

  assert:
    that:

      - consul_server_support is iterable
      - '"{{ ansible_system | lower }}-{{ ansible_architecture | lower }}" in consul_server_support | lower'

  tags:
    - asteria
    - hashicorp
    - consul
    - server
    - verify

###################################################################################################
