###################################################################################################

- name: setup

  setup:

  tags:
    - asteria
    - shared

###################################################################################################
